name: marcocalzolari
favicon: null
layout_spectrum: 0.30978778121061623
typography_spectrum: 0.5584807302802801
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6331872993614525
  lightness: 0.7303447180893272
  saturation: 0.04672202514484525
  rhythmicContrast: 0.6834862329997122
purpose: []
